export enum Color {
  PRIMARY = "#7B61FF",
  PRIMARY_LIGHT = "#917CFF",
  SECONDARY = "#80858B",
  BLACK = "#000",
  DARK = "#242426",
  GRAPHITE = "#323537",
  ERROR = "#FF5154",
  LIGHT = "#AFB2B6",
  WHITE = "#FFF",
  GREEN = "#00A340",
  YELLOW = "#F3A608",
  ORANGE = "#F45D2D",

  WHITE_THEME = "var(--white)",
  DARK_THEME = "var(--dark)",
  LIGHT_THEME = "var(--light)",
  SECONDARY_THEME = "var(--secondary)",
  GREY_THEME = "var(--grey)",
  MURK_THEME = "var(--murk)",
}
